# Generated by Django 4.2.7 on 2023-12-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gold_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
