# Generated by Django 4.2.7 on 2024-02-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_feedback_remove_order_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderedProduct',
        ),
    ]
