# Generated by Django 4.2.7 on 2024-02-27 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='order',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
