# Generated by Django 4.2.7 on 2024-02-27 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_remove_orderedproduct_order_orderedproduct_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
