# Generated by Django 4.2.7 on 2024-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_orderedproduct_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPurityPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_composition', models.FloatField()),
                ('density', models.FloatField()),
                ('purity', models.FloatField()),
            ],
        ),
    ]
