# Generated by Django 4.2.7 on 2024-03-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_goldpuritypredictionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoldPurityPredictionModel',
        ),
    ]
