# Generated by Django 4.2.7 on 2024-03-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_delete_goldpuritypredictionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_purity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
