# Generated by Django 4.2.7 on 2024-03-14 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_golditemnew_calculated_purity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
