# Generated by Django 4.2.7 on 2024-03-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_remove_orderedproduct_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
