# Generated by Django 4.2.7 on 2024-03-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_payment_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
