# Generated by Django 4.2.7 on 2024-03-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_orderedproduct_razorpaypayment_ordered_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaypayment',
            name='razorpay_signature',
        ),
    ]
