# Generated by Django 4.2.7 on 2024-03-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_remove_razorpaypayment_razorpay_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaypayment',
            name='ordered_products',
        ),
        migrations.RemoveField(
            model_name='razorpaypayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderedProduct',
        ),
        migrations.DeleteModel(
            name='RazorpayPayment',
        ),
    ]
