# Generated by Django 4.2.7 on 2024-03-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0035_golditemnew_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golditemnew',
            name='density',
        ),
    ]
