# Generated by Django 4.2.7 on 2024-04-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0036_remove_golditemnew_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golditemnew',
            name='calculated_purity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='golditemnew',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.product'),
        ),
        migrations.AlterField(
            model_name='golditemnew',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='golditemnew',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
