# Generated by Django 4.2.7 on 2024-04-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0037_alter_golditemnew_calculated_purity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golditemnew',
            name='calculated_purity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='golditemnew',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_item', to='userapp.product'),
        ),
        migrations.AlterField(
            model_name='golditemnew',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='golditemnew',
            name='weight',
            field=models.FloatField(),
        ),
    ]
