# Generated by Django 4.2.7 on 2024-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0038_alter_golditemnew_calculated_purity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='density_gold_alloy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
