# Generated by Django 4.2.7 on 2024-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0039_product_density_gold_alloy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='predicted_purity_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
