# Generated by Django 4.2.7 on 2024-04-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0041_golditemnew_predicted_purity_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golditemnew',
            name='calculated_purity',
        ),
    ]
