# Generated by Django 4.2.7 on 2024-04-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0042_remove_golditemnew_calculated_purity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='estimated_purity',
        ),
    ]
